//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Models.FileManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepositoryPermissions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RepositoryPermissions()
        {
            this.UsersRepositoryPermissions = new HashSet<UsersRepositoryPermissions>();
        }
    
        public int ID { get; set; }
        public string Repository_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersRepositoryPermissions> UsersRepositoryPermissions { get; set; }
    }
}
