//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Models.FileManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersModules
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int Permission_ID { get; set; }
    
        public virtual Modules Modules { get; set; }
    }
}
