//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Models.Mitigate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MitigateEntities : DbContext
    {
        public MitigateEntities()
            : base("name=MitigateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boards> Boards { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<UserBoards> UserBoards { get; set; }
        public virtual DbSet<UserPermissions> UserPermissions { get; set; }
        public virtual DbSet<UsersLevelPermissions> UsersLevelPermissions { get; set; }
        public virtual DbSet<LevelPermissions> LevelPermissions { get; set; }
        public virtual DbSet<StaticBoards> StaticBoards { get; set; }
        public virtual DbSet<StaticUserBoards> StaticUserBoards { get; set; }
    }
}
