//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Models.Mitigate
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticUserBoards
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int Board_ID { get; set; }
        public Nullable<int> Add_User_ID { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Modified_User_ID { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual StaticBoards StaticBoards { get; set; }
    }
}
