//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Models.Mitigate
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticBoards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaticBoards()
        {
            this.StaticUserBoards = new HashSet<StaticUserBoards>();
        }
    
        public int ID { get; set; }
        public string BoardName { get; set; }
        public Nullable<int> ShowInMenu { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaticUserBoards> StaticUserBoards { get; set; }
    }
}
