//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID { get; set; }
        public string ISO { get; set; }
        public string Name { get; set; }
        public string Nice_Name { get; set; }
        public string ISO3 { get; set; }
        public Nullable<int> Number_Code { get; set; }
        public Nullable<int> Phone_Code { get; set; }
        public string Flag { get; set; }
    }
}
