//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Models.DAC6
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LevelPermission()
        {
            this.UserLevelPermission = new HashSet<UserLevelPermission>();
        }
    
        public int ID { get; set; }
        public string Permission { get; set; }
        public string Description { get; set; }
        public bool Visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLevelPermission> UserLevelPermission { get; set; }
    }
}
