//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Models.DAC6
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLevelPermission
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int LevelPermissionId { get; set; }
    
        public virtual LevelPermission LevelPermission { get; set; }
    }
}
